version: "3.9"

services:
  pawnie:
    image: holloow313/pawnie:latest
    container_name: pawnie
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      JWT_SECRET: "${JWT_SECRET:-change-me}"
      DATABASE_URL: "${DATABASE_URL:-file:./data/pawnie.db}"
      UPLOAD_DIR: "${UPLOAD_DIR:-./data/uploads}"
      NEXT_PUBLIC_APP_URL: "${NEXT_PUBLIC_APP_URL:-http://localhost:3000}"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000"]
      interval: 20s
      timeout: 5s
      retries: 5
